language: php
php:
- 7.1.3
before_script:
- mysql -e 'CREATE DATABASE rounds_testing;'
- composer self-update
- composer install --prefer-source --no-interaction --dev
script:
- vendor/bin/phpunit
deploy:
  provider: heroku
  api_key:
    secure: R4CprQXyO+DuH+vzpnpCWZkkVC1sR/QfFOsVcum0jLIjfWrRW7V4foqQPCuMNhEr55tm1QZ0ueQtUh2TKim3LhqoMydmqh9F3QPP2ysjGYlnT7t+eAo3TbnSM3PwcD/j45qlnrGAL5mHV10Qj8tm8NGz0e1P+X5/OobObi9p6DA1tXdWPhDtrF0s8GJ+YcCImfjfOSc+YI8cl8EBdh+fDzwvjFLPZsRX6ZvCEyCg0GK6lNSsKV1XYKndZFMmvwDJrAtNzCX4EPK35O7YdgxXm9337Cr9w4bpdZHau/1mzEJvgwg9VsgnV4/Wyyce79pDENd+cbKtodHhwp2SATGEjpcgPGrU8FjuzUrtTrtEj9a2bBE1SImE3GPVk8Q9rLX0YlNQT8BRPMbXaaVZP6UjhzsRN5muTYwfbEcay/hGiJbsVD+q5S/xxSDdwxNtZdImss9RW3M+L7DTQsVfddkUfVjgH1QCZknHtR6Jj8RcfbhMwcSdrwcdLkGdB3JbW9zDw4lAb3hoo3Z1Ul1cBmLy8DZ+1N59CXarSzeI8uF+yEckySLuJukQWj/unBS11vgbJjW2ja2CJt22Oag1HUrJQOg9oY/lhXg1bmW/6UJtkTldnsWfZ+Jy9kYFd59e3kYGcjQc091Ebh7dz7uO0orDpyboqu0zJxMVUzbASH43U8A=
  app: smaa-ch
  run: php artisan migrate --force
